all:
  children:
    ios:
      hosts: 
        SWEx-CC7-acc1: 
        SWEx-CC7-acc2: 
        SWEx-CC8-acc1: 
        SWEx-CC8-acc2: 
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_ssh_pass: '{{password}}'
        ansible_user: '{{username}}'
  vars:
    ansible_python_interpreter: /usr/bin/python3
